site_name: kbj's cheatsheets
nav:
  - ğŸ¡ Home: index.md
  - ğŸ“š References: references/index.md
  - ğŸ§‘â€ğŸ“ Learning: learning/index.md
theme:
  name: material
  language: en
  font:
    text: Inconsolata
    code: Inconsolata
  logo: img/logo.png
  favicon: img/logo.ico
  palette:
    scheme: slate
    primary: blue grey
    accent: yellow
  features:
    - header.autohide
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.sections
    - navigation.expand
extra_css: [cheatsheets.css]
plugins:
  - offline
  - search
  - tags
